<?php

namespace App\Http\Requests;

use Anik\Form\FormRequest;

class StoreTransactionRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    protected function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    protected function rules(): array
    {
        return [
            'value' => 'required|numeric',
            'id_payer' => 'required|integer',
            'id_payee' => 'required|integer',
        ];
    }

    protected function messages(): array
    {
/*        if($this->has('message'))
        {
            return parent::messages(); // TODO: Change the autogenerated stub
        }*/

        return [
            'required' => 'O campo :attribute é obrigatório.',
            'integer' => 'O campo :attribute deve ter do tipo inteiro.',
            'numeric' => 'O campo :attribute deve ser do tipo númerico.'
        ];
    }
}
