<?php

namespace App\Http\Requests;

use Anik\Form\FormRequest;

class StoreUserRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    protected function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    protected function rules(): array
    {
        return [
          'name' => 'required|min:7',
          'email' => 'required|email',
          'password' => 'required|string|min:8',
          'balance' => 'required|numeric|min:0',
          'user_type' => 'required|string|min:1|max:1',
          'document' => 'required|string|min:11|max:14',
        ];
    }

    protected function messages(): array
    {
/*        if($this->has('message'))
        {
            return parent::messages(); // TODO: Change the autogenerated stub
        }*/

        return [
            'required' => 'O campo :attribute é obrigatório.',
            'min' => 'O campo :attribute deve ter pelo menos :min caracteres.',
            'email' => 'O campo :attribute deve ser do tipo e-mail.',
            'string' => 'O campo :attribute deve ser do tipo string.',
            'max' => 'O campo :attribute não pode ter mais do que :max caracteres',
            'numeric' => 'O campo :attribute deve ser do tipo númerico.'
        ];
    }
}
